language: c

compiler:
  - gcc

git:
  depth: 10

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt install bison texinfo; fi

matrix:
  include:
    - os: linux
      script: ./build-gcc/build-aptex.sh
    - os: osx
      osx_image: xcode9.1
      script: ./build-gcc/build-aptex.sh
