language: c

compiler:
  - gcc

git:
  depth: 5

matrix:
  include:
    - os: linux
      script: sh -c "apt update; apt install -y automake autoconf libtool texinfo texi2html gcc ruby make; ./build-gcc/build-aptex.sh"
    - os: osx
      osx_image: xcode10
      script: ./build-gcc/build-aptex.sh
