language: c

compiler:
  - gcc

git:
  depth: 5

dist: focal

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt update
        - sudo apt install -y automake autoconf libtool texinfo texi2html gcc ruby make
      script: ./build-gcc/build-aptex.sh
    - os: osx
      osx_image: xcode10
      script: ./build-gcc/build-aptex.sh
