language: c

compiler:
    - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - info
            - bison
      script: ./build-aptex.sh
    - os: osx
      osx_image: xcode9.1
      script: ./build-aptex.sh
