language: c

compiler:
  - gcc

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt install bison texi2html; fi

matrix:
  include:
    - os: linux
      script: ./build-aptex.sh
    - os: osx
      osx_image: xcode9.1
      script: ./build-aptex.sh
