platform:
  - Any CPU
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
build_script:
- cmd: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64
- cmd: cd build-msvc
- cmd: build.bat
